// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package twogapplicationinsights.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.webui.CustomJavaAction;
import com.microsoft.applicationinsights.telemetry.MetricTelemetry;
import twogapplicationinsights.ApplicationInsightsLogger;
import twogapplicationinsights.helpers.TelemetryConverterHelper;

public class TrackMetric extends CustomJavaAction<java.lang.Boolean>
{
	private java.lang.String InstrumentationKey;
	private IMendixObject __Metric;
	private twogapplicationinsights.proxies.MetricTelemetry Metric;

	public TrackMetric(IContext context, java.lang.String InstrumentationKey, IMendixObject Metric)
	{
		super(context);
		this.InstrumentationKey = InstrumentationKey;
		this.__Metric = Metric;
	}

	@Override
	public java.lang.Boolean executeAction() throws Exception
	{
		this.Metric = __Metric == null ? null : twogapplicationinsights.proxies.MetricTelemetry.initialize(getContext(), __Metric);

		// BEGIN USER CODE

		// Convert the Mendix Metric object to the AppInsights Metric object
		MetricTelemetry mt = TelemetryConverterHelper.convertMetricTelemetry(Metric);

		// Step 2: send the metric to AppInsights loggers
		if (InstrumentationKey == null || InstrumentationKey.length() == 0)
		{
			ApplicationInsightsLogger.sendMetricToAll(mt);
		}
		else
		{
			ApplicationInsightsLogger logger = ApplicationInsightsLogger.getInstance(InstrumentationKey);
			logger.sendMetric(mt);
		}

		return Boolean.TRUE;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public java.lang.String toString()
	{
		return "TrackMetric";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
