// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package twogapplicationinsights.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.webui.CustomJavaAction;
import com.microsoft.applicationinsights.telemetry.ExceptionTelemetry;
import twogapplicationinsights.ApplicationInsightsLogger;
import twogapplicationinsights.helpers.TelemetryConverterHelper;

public class TrackException extends CustomJavaAction<java.lang.Boolean>
{
	private java.lang.String InstrumentationKey;
	private IMendixObject __Exception;
	private twogapplicationinsights.proxies.ExceptionTelemetry Exception;

	public TrackException(IContext context, java.lang.String InstrumentationKey, IMendixObject Exception)
	{
		super(context);
		this.InstrumentationKey = InstrumentationKey;
		this.__Exception = Exception;
	}

	@Override
	public java.lang.Boolean executeAction() throws Exception
	{
		this.Exception = __Exception == null ? null : twogapplicationinsights.proxies.ExceptionTelemetry.initialize(getContext(), __Exception);

		// BEGIN USER CODE

		// Convert the Mendix Exception object to the AppInsights Exception object
		ExceptionTelemetry et = TelemetryConverterHelper.convertExceptionTelemetry(Exception);

		// Step 2: send the metric to AppInsights loggers
		if (InstrumentationKey == null || InstrumentationKey.length() == 0)
		{
			ApplicationInsightsLogger.sendExceptionToAll(et);
		}
		else
		{
			ApplicationInsightsLogger logger = ApplicationInsightsLogger.getInstance(InstrumentationKey);
			logger.sendException(et);
		}

		return Boolean.TRUE;

		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public java.lang.String toString()
	{
		return "TrackException";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
