// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package twogapplicationinsights.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.webui.CustomJavaAction;
import com.microsoft.applicationinsights.telemetry.EventTelemetry;
import twogapplicationinsights.ApplicationInsightsLogger;
import twogapplicationinsights.helpers.TelemetryConverterHelper;

public class TrackEvent extends CustomJavaAction<java.lang.Boolean>
{
	private java.lang.String InstrumentationKey;
	private IMendixObject __Event;
	private twogapplicationinsights.proxies.EventTelemetry Event;

	public TrackEvent(IContext context, java.lang.String InstrumentationKey, IMendixObject Event)
	{
		super(context);
		this.InstrumentationKey = InstrumentationKey;
		this.__Event = Event;
	}

	@java.lang.Override
	public java.lang.Boolean executeAction() throws Exception
	{
		this.Event = __Event == null ? null : twogapplicationinsights.proxies.EventTelemetry.initialize(getContext(), __Event);

		// BEGIN USER CODE

		// Convert the Mendix Event object to the AppInsights Event object
		EventTelemetry et = TelemetryConverterHelper.convertEventTelemetry(Event);

		// Step 2: send the metric to AppInsights loggers
		if (InstrumentationKey == null || InstrumentationKey.length() == 0)
		{
			ApplicationInsightsLogger.sendEventToAll(et);
		}
		else
		{
			ApplicationInsightsLogger logger = ApplicationInsightsLogger.getInstance(InstrumentationKey);
			logger.sendEvent(et);
		}

		return Boolean.TRUE;

		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "TrackEvent";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
