// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package twogapplicationinsights.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.webui.CustomJavaAction;
import com.microsoft.applicationinsights.telemetry.Duration;
import com.microsoft.applicationinsights.telemetry.RequestTelemetry;
import twogapplicationinsights.ApplicationInsightsLogger;
import twogapplicationinsights.helpers.DataHelper;

public class TrackRequest extends CustomJavaAction<java.lang.Boolean>
{
	private java.lang.String InstrumentationKey;
	private IMendixObject __Request;
	private twogapplicationinsights.proxies.RequestTelemetry Request;

	public TrackRequest(IContext context, java.lang.String InstrumentationKey, IMendixObject Request)
	{
		super(context);
		this.InstrumentationKey = InstrumentationKey;
		this.__Request = Request;
	}

	@Override
	public java.lang.Boolean executeAction() throws Exception
	{
		this.Request = __Request == null ? null : twogapplicationinsights.proxies.RequestTelemetry.initialize(getContext(), __Request);

		// BEGIN USER CODE

		// Step 1: Convert the Mendix Metric object to the AppInsights Metric object
		RequestTelemetry rt = new RequestTelemetry();

		rt.setName(Request.getName());
		rt.setUrl(Request.getUrl());
		rt.setTimestamp(Request.getTimestamp());

		rt.setDuration(new Duration(Request.getDuration()));
		rt.setResponseCode(Request.getResponseCode());

		rt.setSuccess(Request.getSuccess());
		rt.setSource(Request.getSource());

		rt.setSamplingPercentage(Request.getSamplingPercentage().doubleValue());

		DataHelper.addToTelemetry(rt, Request.getCustomProperties());

		// Step 2: send the metric to AppInsights loggers
		if (InstrumentationKey == null || InstrumentationKey.length() == 0)
		{
			ApplicationInsightsLogger.sendRequestToAll(rt);
		}
		else
		{
			ApplicationInsightsLogger logger = ApplicationInsightsLogger.getInstance(InstrumentationKey);
			logger.sendRequest(rt);
		}

		return Boolean.TRUE;

		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public java.lang.String toString()
	{
		return "TrackRequest";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
