// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package twogapplicationinsights.actions;

import java.util.Map;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import twogapplicationinsights.ApplicationInsightsLogger;
import twogapplicationinsights.helpers.DataHelper;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class TrackTrace extends CustomJavaAction<java.lang.Boolean>
{
	private java.lang.String InstrumentationKey;
	private java.lang.String Message;
	private java.util.List<IMendixObject> __Properties;
	private java.util.List<twogapplicationinsights.proxies.AppInsightProperty> Properties;

	public TrackTrace(IContext context, java.lang.String InstrumentationKey, java.lang.String Message, java.util.List<IMendixObject> Properties)
	{
		super(context);
		this.InstrumentationKey = InstrumentationKey;
		this.Message = Message;
		this.__Properties = Properties;
	}

	@java.lang.Override
	public java.lang.Boolean executeAction() throws Exception
	{
		this.Properties = new java.util.ArrayList<twogapplicationinsights.proxies.AppInsightProperty>();
		if (__Properties != null)
			for (IMendixObject __PropertiesElement : __Properties)
				this.Properties.add(twogapplicationinsights.proxies.AppInsightProperty.initialize(getContext(), __PropertiesElement));

		// BEGIN USER CODE
		
		//Step 1: convert the properties
		Map<String, String> properties = DataHelper.convertProperties(Properties);
		if (InstrumentationKey == null || InstrumentationKey.length() == 0)
		{
			ApplicationInsightsLogger.sendTraceToAll(Message, properties);
		}
		else
		{
			ApplicationInsightsLogger logger = ApplicationInsightsLogger.getInstance(InstrumentationKey);
			logger.sendTrace(Message, properties);
		}

		return Boolean.TRUE;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "TrackTrace";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
