// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package twogapplicationinsights.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.webui.CustomJavaAction;
import com.microsoft.applicationinsights.telemetry.TraceTelemetry;
import twogapplicationinsights.ApplicationInsightsLogger;
import twogapplicationinsights.helpers.TelemetryConverterHelper;

public class TrackTraceExtended extends CustomJavaAction<java.lang.Boolean>
{
	private java.lang.String InstrumentationKey;
	private IMendixObject __Trace;
	private twogapplicationinsights.proxies.TraceTelemetry Trace;

	public TrackTraceExtended(IContext context, java.lang.String InstrumentationKey, IMendixObject Trace)
	{
		super(context);
		this.InstrumentationKey = InstrumentationKey;
		this.__Trace = Trace;
	}

	@java.lang.Override
	public java.lang.Boolean executeAction() throws Exception
	{
		this.Trace = __Trace == null ? null : twogapplicationinsights.proxies.TraceTelemetry.initialize(getContext(), __Trace);

		// BEGIN USER CODE

		// Step 1: Convert the Mendix Trace object to the AppInsights Trace object
		TraceTelemetry tt = TelemetryConverterHelper.convertTraceTelemetry(Trace);

		// Step 2: send the metric to AppInsights loggers
		if (InstrumentationKey == null || InstrumentationKey.length() == 0)
		{
			ApplicationInsightsLogger.sendTraceToAll(tt);
		}
		else
		{
			ApplicationInsightsLogger logger = ApplicationInsightsLogger.getInstance(InstrumentationKey);
			logger.sendTrace(tt);
		}

		return Boolean.TRUE;

		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "TrackTraceExtended";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
