// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package twogapplicationinsights.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.webui.CustomJavaAction;
import com.microsoft.applicationinsights.telemetry.PageViewTelemetry;
import twogapplicationinsights.ApplicationInsightsLogger;
import twogapplicationinsights.helpers.TelemetryConverterHelper;

public class TrackPageView extends CustomJavaAction<java.lang.Boolean>
{
	private java.lang.String InstrumentationKey;
	private IMendixObject __PageView;
	private twogapplicationinsights.proxies.PageViewTelemetry PageView;

	public TrackPageView(IContext context, java.lang.String InstrumentationKey, IMendixObject PageView)
	{
		super(context);
		this.InstrumentationKey = InstrumentationKey;
		this.__PageView = PageView;
	}

	@java.lang.Override
	public java.lang.Boolean executeAction() throws Exception
	{
		this.PageView = __PageView == null ? null : twogapplicationinsights.proxies.PageViewTelemetry.initialize(getContext(), __PageView);

		// BEGIN USER CODE

		// Convert the Mendix PageView object to the AppInsights PageView object
		PageViewTelemetry pvt = TelemetryConverterHelper.convertPageViewTelemetry(PageView);

		// Step 2: send the metric to AppInsights loggers
		if (InstrumentationKey == null || InstrumentationKey.length() == 0)
		{
			ApplicationInsightsLogger.sendPageViewToAll(pvt);
		}
		else
		{
			ApplicationInsightsLogger logger = ApplicationInsightsLogger.getInstance(InstrumentationKey);
			logger.sendPageView(pvt);
		}

		return Boolean.TRUE;

		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "TrackPageView";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
