// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package demo.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.MendixRuntimeException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class Microflows
{
	// These are the microflows for the Demo module
	public static twogapplicationinsights.proxies.DependencyTelemetry dS_NewDependencyMessage(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		IMendixObject result = (IMendixObject)Core.microflowCall("Demo.DS_NewDependencyMessage").withParams(params).execute(context);
		return result == null ? null : twogapplicationinsights.proxies.DependencyTelemetry.initialize(context, result);
	}
	public static twogapplicationinsights.proxies.EventTelemetry dS_NewEventMessage(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		IMendixObject result = (IMendixObject)Core.microflowCall("Demo.DS_NewEventMessage").withParams(params).execute(context);
		return result == null ? null : twogapplicationinsights.proxies.EventTelemetry.initialize(context, result);
	}
	public static twogapplicationinsights.proxies.ExceptionTelemetry dS_NewExceptionMessage(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		IMendixObject result = (IMendixObject)Core.microflowCall("Demo.DS_NewExceptionMessage").withParams(params).execute(context);
		return result == null ? null : twogapplicationinsights.proxies.ExceptionTelemetry.initialize(context, result);
	}
	public static twogapplicationinsights.proxies.MetricTelemetry dS_NewMetricMessage(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		IMendixObject result = (IMendixObject)Core.microflowCall("Demo.DS_NewMetricMessage").withParams(params).execute(context);
		return result == null ? null : twogapplicationinsights.proxies.MetricTelemetry.initialize(context, result);
	}
	public static twogapplicationinsights.proxies.PageViewTelemetry dS_NewPageViewMessage(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		IMendixObject result = (IMendixObject)Core.microflowCall("Demo.DS_NewPageViewMessage").withParams(params).execute(context);
		return result == null ? null : twogapplicationinsights.proxies.PageViewTelemetry.initialize(context, result);
	}
	public static twogapplicationinsights.proxies.RequestTelemetry dS_NewRequestMessage(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		IMendixObject result = (IMendixObject)Core.microflowCall("Demo.DS_NewRequestMessage").withParams(params).execute(context);
		return result == null ? null : twogapplicationinsights.proxies.RequestTelemetry.initialize(context, result);
	}
	public static twogapplicationinsights.proxies.TraceTelemetry dS_NewTraceMessage(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		IMendixObject result = (IMendixObject)Core.microflowCall("Demo.DS_NewTraceMessage").withParams(params).execute(context);
		return result == null ? null : twogapplicationinsights.proxies.TraceTelemetry.initialize(context, result);
	}
	public static void iVK_SendDependencyMessage(IContext context, twogapplicationinsights.proxies.DependencyTelemetry _dependencyTelemetry)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("DependencyTelemetry", _dependencyTelemetry == null ? null : _dependencyTelemetry.getMendixObject());
		Core.microflowCall("Demo.IVK_SendDependencyMessage").withParams(params).execute(context);
	}
	public static void iVK_SendEventMessage(IContext context, twogapplicationinsights.proxies.EventTelemetry _eventTelemetry)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("EventTelemetry", _eventTelemetry == null ? null : _eventTelemetry.getMendixObject());
		Core.microflowCall("Demo.IVK_SendEventMessage").withParams(params).execute(context);
	}
	public static void iVK_SendExceptionMessage(IContext context, twogapplicationinsights.proxies.ExceptionTelemetry _exceptionTelemetry)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("ExceptionTelemetry", _exceptionTelemetry == null ? null : _exceptionTelemetry.getMendixObject());
		Core.microflowCall("Demo.IVK_SendExceptionMessage").withParams(params).execute(context);
	}
	public static void iVK_SendMetricMessage(IContext context, twogapplicationinsights.proxies.MetricTelemetry _metricTelemetry)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("MetricTelemetry", _metricTelemetry == null ? null : _metricTelemetry.getMendixObject());
		Core.microflowCall("Demo.IVK_SendMetricMessage").withParams(params).execute(context);
	}
	public static void iVK_SendPageViewMessage(IContext context, twogapplicationinsights.proxies.PageViewTelemetry _pageViewTelemetry)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("PageViewTelemetry", _pageViewTelemetry == null ? null : _pageViewTelemetry.getMendixObject());
		Core.microflowCall("Demo.IVK_SendPageViewMessage").withParams(params).execute(context);
	}
	public static void iVK_SendRequestMessage(IContext context, twogapplicationinsights.proxies.RequestTelemetry _requestTelemetry)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("RequestTelemetry", _requestTelemetry == null ? null : _requestTelemetry.getMendixObject());
		Core.microflowCall("Demo.IVK_SendRequestMessage").withParams(params).execute(context);
	}
	public static void iVK_SendTraceExtendedMessage(IContext context, twogapplicationinsights.proxies.TraceTelemetry _traceTelemetry)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("TraceTelemetry", _traceTelemetry == null ? null : _traceTelemetry.getMendixObject());
		Core.microflowCall("Demo.IVK_SendTraceExtendedMessage").withParams(params).execute(context);
	}
	public static void iVK_SendTraceMessage(IContext context, twogapplicationinsights.proxies.TraceTelemetry _traceTelemetry)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("TraceTelemetry", _traceTelemetry == null ? null : _traceTelemetry.getMendixObject());
		Core.microflowCall("Demo.IVK_SendTraceMessage").withParams(params).execute(context);
	}
	public static boolean sUB_AfterStartup(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		return (java.lang.Boolean) Core.microflowCall("Demo.SUB_AfterStartup").withParams(params).execute(context);
	}
	public static java.util.List<twogapplicationinsights.proxies.MetricData> sUB_CreateAditionalMetricData(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		java.util.List<IMendixObject> objs = Core.microflowCall("Demo.SUB_CreateAditionalMetricData").withParams(params).execute(context);
		java.util.List<twogapplicationinsights.proxies.MetricData> result = null;
		if (objs != null)
		{
			result = new java.util.ArrayList<>();
			for (IMendixObject obj : objs)
				result.add(twogapplicationinsights.proxies.MetricData.initialize(context, obj));
		}
		return result;
	}
	public static java.util.List<twogapplicationinsights.proxies.AppInsightProperty> sUB_CreateAditionalProperty(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		java.util.List<IMendixObject> objs = Core.microflowCall("Demo.SUB_CreateAditionalProperty").withParams(params).execute(context);
		java.util.List<twogapplicationinsights.proxies.AppInsightProperty> result = null;
		if (objs != null)
		{
			result = new java.util.ArrayList<>();
			for (IMendixObject obj : objs)
				result.add(twogapplicationinsights.proxies.AppInsightProperty.initialize(context, obj));
		}
		return result;
	}
}