// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package demo.proxies.constants;

import com.mendix.core.Core;

public class Constants
{
	// These are the constants for the Demo module

	public static java.lang.String getAPPLICATION_CONTEXT_ID()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("Demo.APPLICATION_CONTEXT_ID");
	}

	/**
	* fbe62dda-d98d-438b-b351-34b90cb12dfb
	*/
	public static java.lang.String getINSTRUMENTATION_KEY()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("Demo.INSTRUMENTATION_KEY");
	}
}