// This file was generated by Mendix Modeler 7.8.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package demo.proxies.constants;

import com.mendix.core.Core;

public class Constants
{
	// These are the constants for the Demo module

	public static java.lang.String getAPPLICATION_CONTEXT_ID()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("Demo.APPLICATION_CONTEXT_ID");
	}

	public static java.lang.String getINSTRUMENTATION_KEY()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("Demo.INSTRUMENTATION_KEY");
	}
}