// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package twogapplicationinsights.proxies;

public class DependencyTelemetry extends twogapplicationinsights.proxies.TelemetryWithMetricDataBase
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "TwoGApplicationInsights.DependencyTelemetry";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Name("Name"),
		DependencyId("DependencyId"),
		ResultCode("ResultCode"),
		Duration("Duration"),
		Success("Success"),
		Command("Command"),
		TypeName("TypeName"),
		Target("Target"),
		Timestamp("Timestamp"),
		SequenceId("SequenceId"),
		AdditionalMetricData("TwoGApplicationInsights.AdditionalMetricData"),
		CustomProperties("TwoGApplicationInsights.CustomProperties");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public DependencyTelemetry(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "TwoGApplicationInsights.DependencyTelemetry"));
	}

	protected DependencyTelemetry(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject dependencyTelemetryMendixObject)
	{
		super(context, dependencyTelemetryMendixObject);
		if (!com.mendix.core.Core.isSubClassOf("TwoGApplicationInsights.DependencyTelemetry", dependencyTelemetryMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a TwoGApplicationInsights.DependencyTelemetry");
	}

	/**
	 * @deprecated Use 'DependencyTelemetry.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static twogapplicationinsights.proxies.DependencyTelemetry initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return twogapplicationinsights.proxies.DependencyTelemetry.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static twogapplicationinsights.proxies.DependencyTelemetry initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new twogapplicationinsights.proxies.DependencyTelemetry(context, mendixObject);
	}

	public static twogapplicationinsights.proxies.DependencyTelemetry load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return twogapplicationinsights.proxies.DependencyTelemetry.initialize(context, mendixObject);
	}

	/**
	 * @return value of Name
	 */
	public final java.lang.String getName()
	{
		return getName(getContext());
	}

	/**
	 * @param context
	 * @return value of Name
	 */
	public final java.lang.String getName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Name.toString());
	}

	/**
	 * Set value of Name
	 * @param name
	 */
	public final void setName(java.lang.String name)
	{
		setName(getContext(), name);
	}

	/**
	 * Set value of Name
	 * @param context
	 * @param name
	 */
	public final void setName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String name)
	{
		getMendixObject().setValue(context, MemberNames.Name.toString(), name);
	}

	/**
	 * @return value of DependencyId
	 */
	public final java.lang.String getDependencyId()
	{
		return getDependencyId(getContext());
	}

	/**
	 * @param context
	 * @return value of DependencyId
	 */
	public final java.lang.String getDependencyId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.DependencyId.toString());
	}

	/**
	 * Set value of DependencyId
	 * @param dependencyid
	 */
	public final void setDependencyId(java.lang.String dependencyid)
	{
		setDependencyId(getContext(), dependencyid);
	}

	/**
	 * Set value of DependencyId
	 * @param context
	 * @param dependencyid
	 */
	public final void setDependencyId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String dependencyid)
	{
		getMendixObject().setValue(context, MemberNames.DependencyId.toString(), dependencyid);
	}

	/**
	 * @return value of ResultCode
	 */
	public final java.lang.String getResultCode()
	{
		return getResultCode(getContext());
	}

	/**
	 * @param context
	 * @return value of ResultCode
	 */
	public final java.lang.String getResultCode(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ResultCode.toString());
	}

	/**
	 * Set value of ResultCode
	 * @param resultcode
	 */
	public final void setResultCode(java.lang.String resultcode)
	{
		setResultCode(getContext(), resultcode);
	}

	/**
	 * Set value of ResultCode
	 * @param context
	 * @param resultcode
	 */
	public final void setResultCode(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String resultcode)
	{
		getMendixObject().setValue(context, MemberNames.ResultCode.toString(), resultcode);
	}

	/**
	 * @return value of Duration
	 */
	public final java.lang.Long getDuration()
	{
		return getDuration(getContext());
	}

	/**
	 * @param context
	 * @return value of Duration
	 */
	public final java.lang.Long getDuration(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.Duration.toString());
	}

	/**
	 * Set value of Duration
	 * @param duration
	 */
	public final void setDuration(java.lang.Long duration)
	{
		setDuration(getContext(), duration);
	}

	/**
	 * Set value of Duration
	 * @param context
	 * @param duration
	 */
	public final void setDuration(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long duration)
	{
		getMendixObject().setValue(context, MemberNames.Duration.toString(), duration);
	}

	/**
	 * @return value of Success
	 */
	public final java.lang.Boolean getSuccess()
	{
		return getSuccess(getContext());
	}

	/**
	 * @param context
	 * @return value of Success
	 */
	public final java.lang.Boolean getSuccess(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Success.toString());
	}

	/**
	 * Set value of Success
	 * @param success
	 */
	public final void setSuccess(java.lang.Boolean success)
	{
		setSuccess(getContext(), success);
	}

	/**
	 * Set value of Success
	 * @param context
	 * @param success
	 */
	public final void setSuccess(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean success)
	{
		getMendixObject().setValue(context, MemberNames.Success.toString(), success);
	}

	/**
	 * @return value of Command
	 */
	public final java.lang.String getCommand()
	{
		return getCommand(getContext());
	}

	/**
	 * @param context
	 * @return value of Command
	 */
	public final java.lang.String getCommand(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Command.toString());
	}

	/**
	 * Set value of Command
	 * @param command
	 */
	public final void setCommand(java.lang.String command)
	{
		setCommand(getContext(), command);
	}

	/**
	 * Set value of Command
	 * @param context
	 * @param command
	 */
	public final void setCommand(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String command)
	{
		getMendixObject().setValue(context, MemberNames.Command.toString(), command);
	}

	/**
	 * @return value of TypeName
	 */
	public final java.lang.String getTypeName()
	{
		return getTypeName(getContext());
	}

	/**
	 * @param context
	 * @return value of TypeName
	 */
	public final java.lang.String getTypeName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.TypeName.toString());
	}

	/**
	 * Set value of TypeName
	 * @param typename
	 */
	public final void setTypeName(java.lang.String typename)
	{
		setTypeName(getContext(), typename);
	}

	/**
	 * Set value of TypeName
	 * @param context
	 * @param typename
	 */
	public final void setTypeName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String typename)
	{
		getMendixObject().setValue(context, MemberNames.TypeName.toString(), typename);
	}

	/**
	 * @return value of Target
	 */
	public final java.lang.String getTarget()
	{
		return getTarget(getContext());
	}

	/**
	 * @param context
	 * @return value of Target
	 */
	public final java.lang.String getTarget(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Target.toString());
	}

	/**
	 * Set value of Target
	 * @param target
	 */
	public final void setTarget(java.lang.String target)
	{
		setTarget(getContext(), target);
	}

	/**
	 * Set value of Target
	 * @param context
	 * @param target
	 */
	public final void setTarget(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String target)
	{
		getMendixObject().setValue(context, MemberNames.Target.toString(), target);
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final twogapplicationinsights.proxies.DependencyTelemetry that = (twogapplicationinsights.proxies.DependencyTelemetry) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "TwoGApplicationInsights.DependencyTelemetry";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Override
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
