// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package twogapplicationinsights.proxies;

public class TelemetryWithMetricDataBase extends twogapplicationinsights.proxies.TelemetryBase
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "TwoGApplicationInsights.TelemetryWithMetricDataBase";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Timestamp("Timestamp"),
		SequenceId("SequenceId"),
		AdditionalMetricData("TwoGApplicationInsights.AdditionalMetricData"),
		CustomProperties("TwoGApplicationInsights.CustomProperties");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public TelemetryWithMetricDataBase(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "TwoGApplicationInsights.TelemetryWithMetricDataBase"));
	}

	protected TelemetryWithMetricDataBase(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject telemetryWithMetricDataBaseMendixObject)
	{
		super(context, telemetryWithMetricDataBaseMendixObject);
		if (!com.mendix.core.Core.isSubClassOf("TwoGApplicationInsights.TelemetryWithMetricDataBase", telemetryWithMetricDataBaseMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a TwoGApplicationInsights.TelemetryWithMetricDataBase");
	}

	/**
	 * @deprecated Use 'TelemetryWithMetricDataBase.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static twogapplicationinsights.proxies.TelemetryWithMetricDataBase initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return twogapplicationinsights.proxies.TelemetryWithMetricDataBase.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static twogapplicationinsights.proxies.TelemetryWithMetricDataBase initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		if (com.mendix.core.Core.isSubClassOf("TwoGApplicationInsights.DependencyTelemetry", mendixObject.getType()))
			return twogapplicationinsights.proxies.DependencyTelemetry.initialize(context, mendixObject);

		if (com.mendix.core.Core.isSubClassOf("TwoGApplicationInsights.EventTelemetry", mendixObject.getType()))
			return twogapplicationinsights.proxies.EventTelemetry.initialize(context, mendixObject);

		if (com.mendix.core.Core.isSubClassOf("TwoGApplicationInsights.ExceptionTelemetry", mendixObject.getType()))
			return twogapplicationinsights.proxies.ExceptionTelemetry.initialize(context, mendixObject);

		if (com.mendix.core.Core.isSubClassOf("TwoGApplicationInsights.PageViewTelemetry", mendixObject.getType()))
			return twogapplicationinsights.proxies.PageViewTelemetry.initialize(context, mendixObject);

		if (com.mendix.core.Core.isSubClassOf("TwoGApplicationInsights.RequestTelemetry", mendixObject.getType()))
			return twogapplicationinsights.proxies.RequestTelemetry.initialize(context, mendixObject);

		return new twogapplicationinsights.proxies.TelemetryWithMetricDataBase(context, mendixObject);
	}

	public static twogapplicationinsights.proxies.TelemetryWithMetricDataBase load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return twogapplicationinsights.proxies.TelemetryWithMetricDataBase.initialize(context, mendixObject);
	}

	/**
	 * @return value of AdditionalMetricData
	 */
	public final java.util.List<twogapplicationinsights.proxies.MetricData> getAdditionalMetricData() throws com.mendix.core.CoreException
	{
		return getAdditionalMetricData(getContext());
	}

	/**
	 * @param context
	 * @return value of AdditionalMetricData
	 */
	@SuppressWarnings("unchecked")
	public final java.util.List<twogapplicationinsights.proxies.MetricData> getAdditionalMetricData(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		java.util.List<twogapplicationinsights.proxies.MetricData> result = new java.util.ArrayList<twogapplicationinsights.proxies.MetricData>();
		Object valueObject = getMendixObject().getValue(context, MemberNames.AdditionalMetricData.toString());
		if (valueObject == null)
			return result;
		for (com.mendix.systemwideinterfaces.core.IMendixObject mendixObject : com.mendix.core.Core.retrieveIdList(context, (java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier>) valueObject))
			result.add(twogapplicationinsights.proxies.MetricData.initialize(context, mendixObject));
		return result;
	}

	/**
	 * Set value of AdditionalMetricData
	 * @param additionalmetricdata
	 */
	public final void setAdditionalMetricData(java.util.List<twogapplicationinsights.proxies.MetricData> additionalmetricdata)
	{
		setAdditionalMetricData(getContext(), additionalmetricdata);
	}

	/**
	 * Set value of AdditionalMetricData
	 * @param context
	 * @param additionalmetricdata
	 */
	public final void setAdditionalMetricData(com.mendix.systemwideinterfaces.core.IContext context, java.util.List<twogapplicationinsights.proxies.MetricData> additionalmetricdata)
	{
		java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier> identifiers = new java.util.ArrayList<com.mendix.systemwideinterfaces.core.IMendixIdentifier>();
		for (twogapplicationinsights.proxies.MetricData proxyObject : additionalmetricdata)
			identifiers.add(proxyObject.getMendixObject().getId());
		getMendixObject().setValue(context, MemberNames.AdditionalMetricData.toString(), identifiers);
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final twogapplicationinsights.proxies.TelemetryWithMetricDataBase that = (twogapplicationinsights.proxies.TelemetryWithMetricDataBase) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "TwoGApplicationInsights.TelemetryWithMetricDataBase";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Override
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
